### PR TITLE
Allow instancing shadows

### PR DESCRIPTION
**Pull request by GordonTombola**
Sorted the issue, I forgot to test it after attempting to change the shader code for both webgl1 and webgl2, it now passed npm run test

Again, i can add some extra tests in for instanced shadows but will have to wait

### CODE REVIEW

**Comment by jnsmalm** [comment]
Hello! When I try this it works fine in Chrome but crashes in Safari 15.6

image

**Comment by jnsmalm** [comment]
image

**Comment by GordonTombola** [comment]
> image

Cheers, will investigate this!

**Comment by jnsmalm** [comment]
Great!

**Pull request merged**
