### PR TITLE
Added material opacity

### PR DESCRIPTION
**Pull request by vujadin**
Easy way to control material opacity, similar to threejs.

### CODE REVIEW

**Comment by jnsmalm** [comment]
Hey @vujadin 

I'm not sure this is the way to go making it easier to set the opacity for the standard material. Do you think something like this is needed because it's a bit cumbersome to change the opacity as it is right now?

The baseColor on the standard material already supports alpha channel, so it doesn't really makes much sense adding another one? Like this, which one would be used in shader, 0.5 or 0.2?

```
material.baseColor = [1,1,1,0.5]
material.opacity = 0.2
```

I think that either the material should honour the alpha property from the display object, or the opacity/alpha property on the material should just read/write to the baseColor[3] (where the alpha channel is today).

What do you think?

**Comment by vujadin** [comment]
Yes, I just wanted an easier way to control opacity. baseColor[3] value is not (immediately) obvious for everyone, so I went with three.js way - having opacity property. Three.js has 3 component vectors for both color and emissive with opacity as separate property and it makes more sense to me, makes cleaner API...

But this: "_material should honour the alpha property from the display object_" - this makes most sense to me (even if it targets baseColor[3] value).

**Comment by jnsmalm** [comment]
I added a color class and standard material now reads from display object alpha property. https://github.com/jnsmalm/pixi3d/commit/440b36ed8353049a089c6848960a50c763cde398

Do you think it's sufficient?

**Comment by vujadin** [comment]
"_standard material now reads from display object alpha_" - I can't find where this is implemented... Changing object alpha still doesn't do anything for me. Also, lib has grown from ~200KB to ~260KB, looks like gl-matrix is packed in it. Is it now hard dependency for pixi3D?

**Comment by vujadin** [comment]
I figured it out, took me a while... I guess its ok, but I would automatically set material.alphaMode = StandardMaterialAlphaMode.blend if object.alpha < 1.

**Pull request closed without merging**
