### PR TITLE
Esm 5 target

### PR DESCRIPTION
**Pull request by GordonTombola**
failure to extends classes from pixi3d when using es5 and esm if the target is set to es2017

error was:
TypeError: Class constructor Container3D cannot be invoked without 'new'

### CODE REVIEW

**Comment by jnsmalm** [comment]
Could you please provide some steps so I can try to reproduce this error?

**Comment by GordonTombola** [comment]
> Could you please provide some steps so I can try to reproduce this error?

I build out pixi3d's dist and types and copy and replace my existing dist/types folder in a projects my node_modules/pixi3d folder.
When my tsconfig is set to target es5 (for greater browser compatibility), the es target is too high for the underlying javascript to attempt to extend the classes within pixi3d

**Comment by jnsmalm** [comment]
Got it, thanks!

What happened to the package-lock file in this commit? Can you revert those changes?

**Comment by GordonTombola** [comment]
> Got it, thanks!
> 
> What happened to the package-lock file in this commit? Can you revert those changes?

sorted, must have happened when I ran npm install

**Review by jnsmalm — APPROVED** [review]

**Pull request merged**
